import SwiftUI

struct AuthenticationView: View {
    @EnvironmentObject private var session: SessionStore
    @Environment(\.graphQLClient) private var api
    @State private var email = ""; @State private var password = ""; @State private var username = ""; @State private var isRegistering = false; @State private var error: String?; @State private var loading = false
    var body: some View { TaillyScreen { VStack(spacing: 20) { Spacer(); Text("tailly").font(.system(size: 44, weight: .bold)).foregroundStyle(TaillyTheme.cyan); Text("Люди. Истории. Моменты.").foregroundStyle(TaillyTheme.muted); if isRegistering { TextField("Имя пользователя", text: $username).textInputAutocapitalization(.never).textFieldStyle(.roundedBorder) }; TextField("Email", text: $email).textInputAutocapitalization(.never).keyboardType(.emailAddress).textFieldStyle(.roundedBorder); SecureField("Пароль", text: $password).textFieldStyle(.roundedBorder); if let error { Text(error).foregroundStyle(.red).font(.footnote) }; Button(loading ? "Подождите…" : (isRegistering ? "Зарегистрироваться" : "Войти")) { Task { isRegistering ? await register() : await login() } }.buttonStyle(.borderedProminent).disabled(loading || email.isEmpty || password.isEmpty || (isRegistering && username.isEmpty)); Button(isRegistering ? "Уже есть аккаунт? Войти" : "Нет аккаунта? Регистрация") { isRegistering.toggle(); error = nil }.font(.footnote); Spacer() }.padding(24) } }
    private func login() async { loading = true; defer { loading = false }; do { struct Response: Decodable { let login: Tokens }; struct Tokens: Decodable { let accessToken: String; let refreshToken: String }; let data: Response = try await api.perform(GraphQLOperations.login, variables: ["input": .object(["email": .string(email), "password": .string(password)])]); session.save(accessToken: data.login.accessToken, refreshToken: data.login.refreshToken) } catch { self.error = error.localizedDescription } }
    private func register() async { loading = true; defer { loading = false }; do { struct Response: Decodable { let register: Registration }; struct Registration: Decodable { let id: Int }; _ = try await api.perform(GraphQLOperations.register, variables: ["input": .object(["username": .string(username), "email": .string(email), "password": .string(password)])]) as Response; isRegistering = false; self.error = "Регистрация завершена. Войдите в аккаунт." } catch { self.error = error.localizedDescription } }
}
