import SwiftUI

struct ClipsView: View {
    @Environment(\.graphQLClient) private var api; @State private var clips: [Clip] = []; @State private var error: String?
    var body: some View { TaillyScreen { Group { if let error, clips.isEmpty { ContentUnavailableView("Не удалось загрузить клипы", systemImage: "wifi.exclamationmark", description: Text(error)) } else { ScrollView { LazyVStack(spacing: 12) { ForEach(clips) { clip in ClipCard(clip: clip, onLike: { await toggleLike(clip) }) } }.padding() } } }.overlay { if clips.isEmpty && error == nil { ProgressView() } } }.task { await load() } }
    private func load() async { do { let response: ClipsResponse = try await api.perform(GraphQLOperations.clips); clips = response.clips; error = nil } catch { self.error = error.localizedDescription } }
    private func toggleLike(_ clip: Clip) async { do { let operation = clip.isLiked ? GraphQLOperations.unlikeClip : GraphQLOperations.likeClip; let response: ClipLikeResponse = try await api.perform(operation, variables: ["clipId": .int(clip.id)]); guard let index = clips.firstIndex(where: { $0.id == response.id }) else { return }; let old = clips[index]; clips[index] = Clip(id: old.id, title: old.title, videoUrl: old.videoUrl, thumbnailUrl: old.thumbnailUrl, commentsCount: old.commentsCount, likesCount: response.likesCount, isLiked: response.isLiked, createdAt: old.createdAt, author: old.author) } catch { self.error = error.localizedDescription } }
}
private struct ClipsResponse: Decodable { let clips: [Clip] }
private struct ClipLikeResponse: Decodable { let id: Int; let likesCount: Int; let isLiked: Bool }
private struct ClipCard: View { let clip: Clip; let onLike: () async -> Void; @State private var commentsVisible = false
    var body: some View { ZStack(alignment: .bottomLeading) { AsyncImage(url: URL(string: clip.thumbnailUrl ?? clip.videoUrl)) { $0.resizable().scaledToFill() } placeholder: { Rectangle().fill(TaillyTheme.card) }.frame(height: 390).clipped(); LinearGradient(colors: [.clear, .black.opacity(0.85)], startPoint: .center, endPoint: .bottom); VStack(alignment: .leading) { Text(clip.author.username).fontWeight(.bold); Text(clip.title ?? ""); HStack { Button { Task { await onLike() } } label: { Label("\(clip.likesCount)", systemImage: clip.isLiked ? "heart.fill" : "heart") }.tint(clip.isLiked ? .pink : .white); Button { commentsVisible = true } label: { Label("\(clip.commentsCount)", systemImage: "bubble.right") } } }.padding() }.clipShape(RoundedRectangle(cornerRadius: 18)).sheet(isPresented: $commentsVisible) { ClipCommentsSheet(clip: clip) } }
}
private struct ClipCommentsSheet: View { @Environment(\.dismiss) private var dismiss; @Environment(\.graphQLClient) private var api; let clip: Clip; @State private var comments: [ClipComment] = []; @State private var text = ""; @State private var error: String?
    var body: some View { NavigationStack { VStack(spacing: 0) { List(comments) { comment in VStack(alignment: .leading) { Text(comment.author.username).fontWeight(.semibold); Text(comment.content) } }.overlay { if comments.isEmpty && error == nil { ProgressView() } }; if let error { Text(error).font(.caption).foregroundStyle(.red) }; HStack { TextField("Комментарий", text: $text).textFieldStyle(.roundedBorder); Button("Отправить") { Task { await send() } }.disabled(text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty) }.padding() }.navigationTitle("Комментарии").toolbar { ToolbarItem(placement: .topBarTrailing) { Button("Готово") { dismiss() } } } }.task { await load() } }
    private func load() async { do { let response: ClipCommentsResponse = try await api.perform(GraphQLOperations.clipComments, variables: ["clipId": .int(clip.id), "limit": .int(50), "offset": .int(0)]); comments = response.clipComments; error = nil } catch { self.error = error.localizedDescription } }
    private func send() async { let content = text.trimmingCharacters(in: .whitespacesAndNewlines); guard !content.isEmpty else { return }; do { let response: CreateClipCommentResponse = try await api.perform(GraphQLOperations.createClipComment, variables: ["clipId": .int(clip.id), "content": .string(content), "parentCommentId": .null]); comments.append(response.createClipComment); text = ""; error = nil } catch { self.error = error.localizedDescription } }
}
private struct ClipCommentsResponse: Decodable { let clipComments: [ClipComment] }
private struct CreateClipCommentResponse: Decodable { let createClipComment: ClipComment }
