enum GraphQLOperations {
    static let login = "mutation Login($input: LoginInput!) { login(input: $input) { accessToken refreshToken } }"
    static let register = "mutation Register($input: RegisterInput!) { register(input: $input) { id } }"
    static let me = "query Me { me { id email username avatar followersCount followingCount } }"
    static let updateProfile = "mutation UpdateProfile($username: String!, $email: String!, $avatar: String!) { updateProfile(username: $username, email: $email, avatar: $avatar) { id email username avatar followersCount followingCount } }"
    static let changePassword = "mutation ChangePassword($oldPassword: String!, $newPassword: String!) { changePassword(oldPassword: $oldPassword, newPassword: $newPassword) }"
    static let posts = "query Posts($limit: Int!, $offset: Int!) { postsPaginated(limit: $limit, offset: $offset) { id title content commentsCount likesCount isLiked createdAt author { id username avatar } } }"
    static let likePost = "mutation LikePost($postId: Int!) { likePost(postId: $postId) { id likesCount isLiked } }"
    static let unlikePost = "mutation UnlikePost($postId: Int!) { unlikePost(postId: $postId) { id likesCount isLiked } }"
    static let postComments = "query PostComments($postId: Int!) { comments(postID: $postId) { id content parentCommentId createdAt author { id username avatar } } }"
    static let createComment = "mutation CreateComment($postId: Int!, $content: String!, $parentCommentId: Int) { createComment(postId: $postId, content: $content, parentCommentId: $parentCommentId) { id content parentCommentId createdAt author { id username avatar } } }"
    static let createPost = "mutation CreatePost($title: String!, $content: Upload!) { createPost(title: $title, content: $content) { id title content commentsCount likesCount isLiked createdAt author { id username avatar } } }"
    static let createClip = "mutation CreateClip($title: String, $video: Upload!) { createClip(title: $title, video: $video) { id title videoUrl thumbnailUrl commentsCount likesCount isLiked createdAt author { id username avatar } } }"
    static let stories = "query Stories { storyFeed(limit: 20) { items { author { id username avatar } stories { id caption mediaType sourceUrl previewUrl createdAt author { id username avatar } } unseenCount } nextPageToken } }"
    static let markStoriesSeen = "mutation MarkStoriesSeen($events: [StorySeenInput!]!) { markStoriesSeen(events: $events) }"
    static let reactToStory = "mutation ReactToStory($storyId: Int!, $reactionType: StoryReactionType!) { reactToStory(storyId: $storyId, reactionType: $reactionType) { id storyId userId reactionType createdAt } }"
    static let removeStoryReaction = "mutation RemoveStoryReaction($storyId: Int!) { removeStoryReaction(storyId: $storyId) }"
    static let sendStoryReply = "mutation SendStoryReply($storyId: Int!, $replyType: StoryReplyType!, $text: String) { sendStoryReply(storyId: $storyId, replyType: $replyType, text: $text) { id storyId replyType text createdAt sender { id username avatar } } }"
    static let clips = "query Clips { clips(limit: 20, offset: 0) { id title videoUrl thumbnailUrl commentsCount likesCount isLiked createdAt author { id username avatar } } }"
    static let likeClip = "mutation LikeClip($clipId: Int!) { likeClip(clipId: $clipId) { id likesCount isLiked } }"
    static let unlikeClip = "mutation UnlikeClip($clipId: Int!) { unlikeClip(clipId: $clipId) { id likesCount isLiked } }"
    static let clipComments = "query ClipComments($clipId: Int!, $limit: Int, $offset: Int) { clipComments(clipId: $clipId, limit: $limit, offset: $offset) { id clipId content parentCommentId createdAt updatedAt author { id username avatar } } }"
    static let createClipComment = "mutation CreateClipComment($clipId: Int!, $content: String!, $parentCommentId: Int) { createClipComment(clipId: $clipId, content: $content, parentCommentId: $parentCommentId) { id clipId content parentCommentId createdAt updatedAt author { id username avatar } } }"
    static let explore = "query Explore($limit: Int!, $offset: Int!, $contentType: String) { exploreFeed(limit: $limit, offset: $offset, contentType: $contentType) { contentType contentId relevanceScore title mediaUrl thumbnailUrl author { id username avatar } likesCount commentsCount isLiked createdAt } }"
    static let recordExploreInteraction = "mutation RecordExploreInteraction($contentId: Int!, $contentType: String!, $interactionType: String!) { recordExploreInteraction(contentId: $contentId, contentType: $contentType, interactionType: $interactionType) }"
    static let chats = "query Chats($userId: Int!) { getUserChats(userId: $userId) { id user1Id user2Id updatedAt unreadCount lastMessage { id chatId senderId receiverId content status createdAt } } }"
    static let messageStream = "subscription MessageStream($userId: Int!) { messageStream(userId: $userId) { id chatId senderId receiverId content status createdAt } }"
}
